server:
  servlet:
    contextPath: /app
  port: 8080

logging:
  level:
    root: INFO

app:
    params:
      kafka:
        bootstrapAddress: localhost:9092
        groupId: businessConsumerGroupId
        topics:
          businessTopic: business-topic

